version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: "sqlite3:db/development.sqlite3"

  db:
    image: "nouchka/sqlite3:latest"
    stdin_open: true
    tty: true
    volumes:
      - "./db:/var/lib/sqlite"
